### ISSUE TITLE
Website updates

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#116]

**Comment by Florie25** [comment]
- Multi-channel modem product page (aRecorder modem)
- aRecoder page
- UnetStack webpage updates - Subnero branded UnetStack, products, premium agents. Add Subnero branded UnetStack, unet premium agents, Unet Audio (DIY modem for future). Do SEO by Yun Ping to work with Anne.
- Adding videos to our various pages and may be even a dedicate videos page
- Optional upgrades and accessories page - GPS, compass, depth sensor in tech specs sheet, cables, batteries, coprocessor (also update tech specs)

**Comment by manuignatius** [comment]
- [ ] Multi-channel modem product page (aRecorder modem)
- [ ] aRecoder page
- [ ] Add relevant videos to various pages (may be even a dedicate videos page)
- [ ] Publications list to page, oceans tutorials page

```
Tutorials and Workshops :
- Prasad Anjangi,  Shiraz Shahabudeen, Chinmay Pendharkar 2020. "Practical Underwater Software Defined Networking," in IEEE Global OCEANS’20, (Singapore - U.S. Gulf Coast), October 2020. (https://subnero.com/oceans20)
- Prasad Anjangi, Shiraz Shahabudeen, Florie Mancel 2019. "Simulation of  Underwater Communications (SUC'19)" , (NIT Surathkal, India), Dec 2019. 
- Mandar Chitre, Chinmay Pendharkar, Prasad Anjangi, Manu Ignatius, 2018. "Hands-on with software defined modems & underwater networks 2018, (Biograd Na Moru, Croatia), Oct 2018. (https://bts.fer.hr/session/t3-hands-on-with-software-defined-modems-underwater-networks/)
- Prasad Anjangi, Mandar Chitre,  Shiraz Shahabudeen, 2018. "A Tutorial on Underwater Acoustic Networking," in IEEE OCEANS’18, (Kobe, Japan), May 2018. (http://www.oceans18mtsieeekobe.org/tutorial-information/)

Conferences :
- P. Anjangi, M. Chitre, M. Ignatius, C. Pendharkar 2021, September. Distributed Spatial Diversity Enabled Receiver System for an Underwater Acoustic Link. In 2021 Fifth Underwater Communications and Networking Conference (UComms) (pp. 1-5). IEEE. (Accepted to be presented at IEEE UComms'21) 
- P. Anjangi, M. Chitre, A. Gibson, M. Ignatius, C. Pendharkar, A. Kurian, A. Low 2020, August. Diver Communications and Localisation System Using Underwater Acoustics. in IEEE GLOBAL OCEANS’20, (Singapore - U.S. Gulf Coast), October 2020.
- P. Anjangi and M. Chitre, 2018, August. Model-based Data-driven Learning Algorithm for Tuning an Underwater Acoustic Link. In 2018 Fourth Underwater Communications and Networking Conference (UComms) (pp. 1-5). IEEE.
```
- [ ] UnetStack webpage updates
   - [ ] Subnero branded UnetStack
   - [ ] Unet premium agents
   - [ ] Unet Audio
- [ ] Optional upgrades and accessories page
   - GPS
   - compass
   - depth sensor
   - cables
   - batteries (primary, rechargeable, integrated, separate)
   - coprocessor
- [ ] [Placeholder] Upcoming products
- [ ] Modem configurator

**Comment by manuignatius** [comment]
Closing these as these are not valid anymore.
