### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by notthetup** [subnero1/subnero1.github.io#119]
A link to some article from the Chinese Society of Oceanography from some old pulse articles is broken

We link to http://www.cso.org.cn/ggxx/2019/0926/2816.html (iOceans'19)

from

_posts/2019-10-29-Subnero-at-iOcean-Sanya.md
_posts/2019-10-15-Subnero-expands-in-china.md

And http://www.cso.org.cn/ggxx/2019/0926/2816.html gives error page now.

So we can either 

1. Link to the new correct page for the iOceans'19
2. Remove the link but keep the words in our pulse pages.

**Comment by AnneThKu** [comment]
Noting down the broken links from #120 

2018-05-27-UnetStack-Newsletter.md
http://www.oceans18mtsieeekobe.org/social-events/
http://www.oceans18mtsieeekobe.org/tutorial-information/
2019-06-11-UnetStack-Newsletter.md
http://www.oceans19mtsieeemarseille.org/
2019-10-15-Subnero-expands-in-china.md
http://www.smartseatech.com/en/index.aspx
2019-10-29-Subnero-at-iOcean-Sanya.md
http://www.cso.org.cn/ggxx/2019/0926/2816.html
https://singapore20.oceansconference.org/
