### ISSUE TITLE
Update website with latest white paper.

### ISSUE THREAD

**Issue by esthertanhj** [subnero1/subnero1.github.io#135]
@Florie25 and @manuignatius 's help required to review latest SWAN white paper available on [this link](https://drive.google.com/file/d/1Kxaiw9VGg-qD7ov_buaoewZp--cwHG0i/view?usp=sharing). @Esther to update based on the comments provided.

Once the latest white paper has been approved, @AnneThKu to update the website with the latest white paper.

**Comment by Florie25** [comment]
Review completed. Approved

**Comment by manuignatius** [comment]
Looks good to me, @AnneThKu to update the website

**Comment by AnneThKu** [comment]
The latest white paper is updated in the website. Please help to check and confirm.

**Comment by Florie25** [comment]
@AnneThKu the document loaded on the website is the correct one. Thank you.
