### ISSUE TITLE
Rename the class names in modem page

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#148]
Some of the class names as given below does not follow the best practices. Hence needs to be renamed to meaningful names.
- cGBxoB
- bsPRnx
- eyXpDN
- cmXrEt
- gfXsQG
- fuqHMA
- hOXnHC

**Comment by notthetup** [comment]
Where did these get into our codebase? Was this from the original theme?

**Comment by manuignatius** [comment]
Not sure whether this is relevant anymore.
