### ISSUE TITLE
To track the warning about large files

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#149]
Got the below warning while pushing some sources to the test-repo for reviewing the multi-channel changes.
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File brochures/Subnero_M25MS_User_Manual.pdf is 56.24 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File brochures/modem-manual.pdf is 52.75 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File brochures/Subnero_M25MS_User_Manual.pdf is 54.16 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by notthetup** [comment]
Good catch. There are many ways to reduce the size of pdfs, we can consider using one of them. Also do we know why we have so many copies of the manual in the brochures dir?

**Comment by AnneThKu** [comment]
For `Subnero_M25MS_User_Manual.pdf` there is only 1 copy in the folder.

**Comment by AnneThKu** [comment]
Also there is one option provided in the warning, `You may want to try Git Large File Storage - https://git-lfs.github.com.`

**Comment by notthetup** [comment]
How is `brochures/modem-manual.pdf`  different than `brochures/Subnero_M25MS_User_Manual.pdf`

**Comment by manuignatius** [comment]
We do not have this warning anymore.
