### ISSUE TITLE
Podcasts links are broken

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#151]
Below pulse posts are broken:
https://subnero.com/wnc/news/2021/01/02/Build-the-future-podcast.html
https://gearforgesoftware.com/iot-weekly-podcast/iot-weekly-episode-8-podcast/

**Comment by notthetup** [comment]
Maybe the first one we can link to https://podcasts.apple.com/us/podcast/build-the-future/id1516358690 and https://podcasts.apple.com/us/podcast/manu-ignatius-subnero-future-oceans-networks-communication/id1516358690?i=1000503822749

**Comment by notthetup** [comment]
The other one seems to be gone. Maybe we can delete it?

**Comment by AnneThKu** [comment]
Yea, the 2nd one i could not find here also https://www.youtube.com/channel/UC_jIbCn9Dev2RmqNQ25Vs4Q/playlists.
I will remove the 2nd one and fix the first one.

**Comment by AnneThKu** [comment]
Updated the archive version for the first link and removed the second one(https://gearforgesoftware.com/iot-weekly-podcast/iot-weekly-episode-8-podcast/).
