### ISSUE TITLE
Change footer layout

### ISSUE THREAD

**Issue by notthetup** [subnero1/subnero1.github.io#16]
_From @sayanee on September 9, 2018 10:26_

## Inspiration

![image](https://user-images.githubusercontent.com/413879/45263542-64267400-b45d-11e8-9247-0a10bda163a2.png)

_Copied from original issue: notthetup/website#7_

**Comment by notthetup** [comment]
Add

- [ ] change to two columns
- [x] line with the Subnero logo in the middle

**Comment by AnneThKu** [comment]
modified footer as below.

<img width="1440" alt="footer" src="https://user-images.githubusercontent.com/42397354/47269761-f3fb2a00-d594-11e8-976c-e5124a6992ed.png">

**Comment by notthetup** [comment]
Do we need to align the columns vertically (like both "Contact Us" and "Support..." start at the same vertical level)? Or is this fine? @manuignatius What do you think?

**Comment by manuignatius** [comment]
Since we have contact us on the right side, i dont think we need another contact us on the left side. Just support and careers will do I think. This can be in separate lines rather than in a single line. Alighting with contact us on the right will also be good IMO.

**Comment by manuignatius** [comment]
Just checked again, both 'contact us' have different behavior. We might want to align them or use different terminology.

**Comment by AnneThKu** [comment]
space made equal above and below the text in the footer.
