### ISSUE TITLE
Website broken links

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#206]
Website Broken Link Check Status : failure.
Details : https://github.com/subnero1/subnero1.github.io/actions/runs/2175275618

**Comment by notthetup** [comment]
We've a CI based broken link checker (https://github.com/subnero1/subnero1.github.io/actions) in the "blog" section of the website (called "pulse"). It's been failing. So we need to go through those errors and remove the dead links..

**Comment by christopherkzj** [comment]
Checked the timeout and deadlinks error, increase the timeout value in the markdown check actions, fixed in pr https://github.com/subnero1/subnero1.github.io/pull/224
