### ISSUE TITLE
Use higher resolution pdf for the WNC whitepaper on the subnero webpage

### ISSUE THREAD

**Issue by sukantahazra** [subnero1/subnero1.github.io#268]
https://subnero.com/brochures/WNC-whitepaper.pdf

The current pdf is pretty low resolution and thus several images are not legible. There is a [higher resolution pdf](https://drive.google.com/file/d/1ZmIuvkXBAuI21pzbTL50obdvXl9Xt-qE/view?usp=share_link) available under the Marketing folder. We could use that instead

![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/66a5b4b3-1038-473c-a2b3-ea23e6c131e8)

![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/e49aa886-386a-47c2-bb5c-fdf83e115375)

**Comment by sukantahazra** [comment]
@manuignatius - I have merged the changes. Do I need to assign this to someone to deploy or what is the process post changes to website content?

**Comment by manuignatius** [comment]
It goes live after the merge. The master branch is the live website.

So, nothing to be done (other than closing the PR).

**Comment by sukantahazra** [comment]
Verified. Looks good.

![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/50b7e75e-6dd9-48dd-a2aa-dd85b381bd68)
