### ISSUE TITLE
Wrong office address on subscription to newsletter confirmation page

### ISSUE THREAD

**Issue by sukantahazra** [subnero1/subnero1.github.io#270]
![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/24bab410-2875-48b4-a558-70cf88c47119)

**Comment by sukantahazra** [comment]
Correct office address is:
```
1003 Bukit Merah Central
#04-05
Singapore 159836
```

**Comment by manuignatius** [comment]
Removed the address altogether. (This is configured in Mailchimp)

**Comment by sukantahazra** [comment]
Looks good.

![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/12b4103c-f813-4d49-ade8-e4fb2e1025b4)

On email

![image](https://github.com/subnero1/subnero1.github.io/assets/6709664/9d941cc0-f5e2-4f17-8d62-bd6b8d374508)
