### ISSUE TITLE
Make pulse page to squares format instead of banner format

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#4]
e.g. Spectrum

Since we have enough blog and news links, it might be better to use a square format.

**Comment by notthetup** [comment]
- [x] 3/4 column using `class="large-4 medium-4 columns"` 
- [x] Remove Read More button
- [x] Add thumbnail images on each pulse post 
- [x] Add default image for pulse post
- [x] Add tags in the post squares

**Comment by manuignatius** [comment]
Updated pulse page with new thumbnail images in pulsepage branch. Review and merge to main branch if all ok.

**Comment by notthetup** [comment]
Let's get in the habit of raising PRs from branches. It's our ISO process too. :)

**Comment by notthetup** [comment]
Raised one : https://github.com/subnero1/subnero1.github.io/pull/61

**Comment by manuignatius** [comment]
Completely agree on the PR, didnt do it since @AnneThKu is the owner as of now. If its ok for her, I was planning to do a PR.

**Comment by manuignatius** [comment]
Updated all thumbnails.
