### ISSUE TITLE
Bigger bolder menu items

### ISSUE THREAD

**Issue by sayanee** [subnero1/subnero1.github.io#42]
## Current situation

![image](https://user-images.githubusercontent.com/413879/46061667-08b4ef80-c19a-11e8-98df-87aa9951d3d1.png)

## Suggested situation

Might need to increase the height of the homepage menu bar.

![image](https://user-images.githubusercontent.com/413879/46061706-21bda080-c19a-11e8-8318-2aeee604118e.png)

**Comment by AnneThKu** [comment]
Text size of the menu increased in the landing page and other pages for bigger screens.

**Comment by notthetup** [comment]
Let's add a screenshot of before and after then we can close this issue.

**Comment by AnneThKu** [comment]
Couldn't see much difference when set as bold. Hence only font-size increased now.
Before:
![Menu_before](https://user-images.githubusercontent.com/42397354/56200613-b1149d80-6071-11e9-8e3e-92a2efc16c4d.png)
After:
![Menu_after](https://user-images.githubusercontent.com/42397354/56200623-b4a82480-6071-11e9-894c-e35cabc97b3f.png)

**Comment by AnneThKu** [comment]
Couldn't see much difference when set as bold. Hence only font-size increased now.
Before:
![Menu_before](https://user-images.githubusercontent.com/42397354/56200613-b1149d80-6071-11e9-8e3e-92a2efc16c4d.png)
After:
![Menu_after](https://user-images.githubusercontent.com/42397354/56200623-b4a82480-6071-11e9-894c-e35cabc97b3f.png)
