### ISSUE TITLE
Hover and click color for homepage menu should be orange

### ISSUE THREAD

**Issue by sayanee** [subnero1/subnero1.github.io#44]
## Current situation

`a:hover` and `a:active` do not change color.

![image](https://user-images.githubusercontent.com/413879/46062186-96dda580-c19b-11e8-932a-17802e5c3af4.png)

## Suggested situation

Try it at [paravelinc](https://paravelinc.com/).

Color change on `hover` or `active` will provide visual feedback to the user on the homepage

![jqzozc9nzx](https://user-images.githubusercontent.com/413879/46062243-c12f6300-c19b-11e8-845f-b4cd39583296.gif)

**Comment by AnneThKu** [comment]
Modified the hover color to orange
![hovercolor1](https://user-images.githubusercontent.com/42397354/47209023-ec375c00-d3c1-11e8-8434-a7931f2f360a.png)
![hovercolor2](https://user-images.githubusercontent.com/42397354/47209057-fd806880-d3c1-11e8-9ed1-577edd203b3f.png)
