### ISSUE TITLE
Add one-liner footer on the homepage

### ISSUE THREAD

**Issue by sayanee** [subnero1/subnero1.github.io#45]
## Current situation

Only a tagline is provided. Slightly more context on the homepage would be good.

![image](https://user-images.githubusercontent.com/413879/46062543-b5906c00-c19c-11e8-8312-b136a4b28124.png)

## Suggested situation

See [paravelinc](https://paravelinc.com/).

![image](https://user-images.githubusercontent.com/413879/46062659-17e96c80-c19d-11e8-97a6-5fd8227bfcf3.png)

```
Follow us on Twitter and GitHub. ©2018 all rights reserved.
```

**Comment by manuignatius** [comment]
It was a conscious decision to keep the clean look and not to include any additional text (e.g. social links).
