### ISSUE TITLE
More padding and 100% width for products

### ISSUE THREAD

**Issue by sayanee** [subnero1/subnero1.github.io#46]
## Current situation

Looks a little cramped up on the [products page](https://subnero.com/products/).

![image](https://user-images.githubusercontent.com/413879/46063037-31d77f00-c19e-11e8-837c-677c0279b319.png)

## Suggested situation

Like [particle products](https://www.particle.io/products/hardware/photon-wifi):

- 100% width alternating between white and gray blocks
- padding within each individual blocks

![image](https://user-images.githubusercontent.com/413879/46063408-4e27eb80-c19f-11e8-906a-10827f642e62.png)

**Comment by manuignatius** [comment]
I think the padding between upper and lower fonts are the same. The difference is in the fact that the particle image has a transparent bg which is not the case with unet image. So, not sure whether this comment is valid, unless we change the image to have a transparent image (modem picture).

**Comment by AnneThKu** [comment]
Should we re-layout the product page as below?

Products Page Full Width - with padding
<img width="953" alt="prodpage_fullwd_withpadding" src="https://user-images.githubusercontent.com/42397354/48388770-88d8e980-e735-11e8-95b7-92a89371f809.png">

Products Page Full Width
<img width="953" alt="productspage_fullwidth" src="https://user-images.githubusercontent.com/42397354/48388772-88d8e980-e735-11e8-83ee-86703cce6b9a.png">
