### ISSUE TITLE
Add brochures to website

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#47]
Need to decide whether we need to add a single page for all brochures or along with relevant product pages

**Comment by notthetup** [comment]
Yes. (https://github.com/subnero1/old_website/tree/master/brochures)

We should add.

- [ ] All the brochures in pdf format into subnero.com/brochures/...
- [ ] Links to the relevant brochures from various product pages.

**Comment by notthetup** [comment]
- AUV Brochure v1.1.pdf - https://subnero.com/products/platinum.html , https://subnero.com/products/silver.html, 
- SWAN Brochure Chinese v3.1.pdf - https://subnero.com/products/swan.html
- SWAN Brochure v3.1.pdf - https://subnero.com/products/swan.html
- Subnero High Speed Modem v1.0.pdf - Not Linked
- Subnero aRecorder v1.1.pdf - Not Linked
- Subnero Modem v3.0.pdf - https://subnero.com/products/platinum.html , https://subnero.com/products/silver.html, https://subnero.com/products/research.html 
- UnetStack Brochure v2.0.pdf - https://subnero.com/products/unet.html
