### ISSUE TITLE
Mobile version of the website

### ISSUE THREAD

**Issue by notthetup** [subnero1/subnero1.github.io#52]
Here is where the website doesn't work on mobile.

- [x] Homepage @ 960x1001

![screenshot 2018-10-19 16 28 05](https://user-images.githubusercontent.com/553140/47206740-fd7d6a00-d3bb-11e8-9a11-439bd74e454c.jpg)

**Comment by notthetup** [comment]
- [x] image and description not aligned properly in product page and swan details from #41

**Comment by notthetup** [comment]
- [ ] image sizes vary in the product page in mobile version https://github.com/subnero1/subnero1.github.io/issues/40

**Comment by AnneThKu** [comment]
Updated some fixes for the mobile version. Below are some of the pending issues:
1. Banner images for size 375x812.
2. Landing page overlay for 375x812.

**Comment by notthetup** [comment]
<img width="1280" alt="screenshot 2018-12-08 14 24 56" src="https://user-images.githubusercontent.com/553140/49682770-0d304980-faf5-11e8-9c6d-9d46b3ce0f19.png">

Underwater Network Stack & Simulator bit seems a little shifted to the right at 1200x800 screen size.

**Comment by AnneThKu** [comment]
the unet image is fixed now.

**Comment by notthetup** [comment]
Still a few bugs left.

![screenshot 2019-02-07 16 56 10](https://user-images.githubusercontent.com/553140/52402269-d54a8000-2afe-11e9-8c3f-a820ab85c451.png)

At small screen sizes, the titles for the Pulse articles might be too big.

![screenshot 2019-02-07 16 56 38](https://user-images.githubusercontent.com/553140/52402285-d8457080-2afe-11e9-9157-893e3fd4b430.png)

**Comment by AnneThKu** [comment]
the Directions to be rendered below the map and above the Subscribe list for mobile version.

**Comment by AnneThKu** [comment]
- Headings to be made standardised across markdown files and font size to be made uniform across all pages.
- Footer link text to be enlarged a bit.

**Comment by AnneThKu** [comment]
Contacts Page and Footer is modified for mobile version. Headings and font-size to be checked in all pages (pending).

![Contact_mobile_1](https://user-images.githubusercontent.com/42397354/56202942-c3dda100-6076-11e9-9422-cfe8097129c0.png)

![Contact_mobile_2](https://user-images.githubusercontent.com/42397354/56202947-c63ffb00-6076-11e9-85eb-6dd59f553dfc.png)

![Footer_mobile](https://user-images.githubusercontent.com/42397354/56202974-d0fa9000-6076-11e9-9c28-d6085cabfdc1.png)

**Comment by AnneThKu** [comment]
@manuignatius .. See if you can reduce the content below, so that font-size if required can be made bigger for this section.

![Screenshot 2019-04-16 at 6 55 51 PM](https://user-images.githubusercontent.com/42397354/56204246-8e868280-6079-11e9-9337-fb5dedd0995b.png)

**Comment by manuignatius** [comment]
1. A team of autonomous low-cost robotic swans that can take in-situ water quality measurements as well as water samples. 
2. A cloud-based system allows the operator to adapt missions quickly based on real-time data. 
3. The SWAN supports industry standard water quality probes and various other sensors.
