### ISSUE TITLE
Add article about modem with coprocessor in pulse page

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#55]
Similar to https://subnero.com/wireless-networked-communications/2017/12/12/Underwater-modem-with-multiple-hydrophones.html

Also add link to https://subnero.com/solutions/

**Comment by prasadtiru** [comment]
Added the article 
https://subnero.com/wnc/2019/04/17/Underwater-modem-with-a-coprocessor.html

Added the link at https://subnero.com/solutions/ as well. 

Feel free to make any changes if required in banner image or content. Closing the issue.
