### ISSUE TITLE
Create these people pages

### ISSUE THREAD

**Issue by prasadtiru** [subnero1/subnero1.github.io#56]
Need to have the following links working:

https://subnero.com/people/prasad
https://subnero.com/people/shiraz

No need for an exposed people page, just a working link is sufficient. 

For reference, take a look at the pages from older website 
https://github.com/subnero1/old_website/tree/master/people

**Comment by AnneThKu** [comment]
Pages are added. Please check and confirm.

**Comment by prasadtiru** [comment]
Works. Thank you @AnneThKu
