### ISSUE TITLE
Automatically detect broken links

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#57]

**Comment by notthetup** [comment]
https://github.com/dkhamsing/awesome_bot

**Comment by AnneThKu** [comment]
Executed awesome_bot on markdown files. Found issues with below links.
-Support->Documentation->fjage developer's guide
http://org-arl.github.io/fjage/doc/html
-2014-06-03-Team-from-Subnero-Awarded-the-Most-Disruptive-Innovation-Award.md
    http://www.hydropreneur.com 
-2015-05-14-UnetStack-Newsletter.md
    http://oceans15mtsieeegenova.org/
-2018-01-19-IOT-Weekly-Podcast.md
    https://gearforgesoftware.com/iot-weekly-podcast/iot-weekly-episode-8-podcast/

**Comment by notthetup** [comment]
My suggestion.

We can change these: 

- Support->Documentation->fjage developer's guide → https://fjage.readthedocs.io/en/latest/

We can remove the links here

- 2014-06-03-Team-from-Subnero-Awarded-the-Most-Disruptive-Innovation-Award.md
- 2015-05-14-UnetStack-Newsletter.md

And we can delete this post entirely.

- 2018-01-19-IOT-Weekly-Podcast.md

What do you think @AnneThKu @manuignatius ?

**Comment by AnneThKu** [comment]
fjage developer's guide updated to latest url.
We can remove only the inactive links in the each of the posts and keep the active links.

**Comment by notthetup** [comment]
Yup. But I think `018-01-19-IOT-Weekly-Podcast.md` doesn't have much of a post. It's just a link.
