### ISSUE TITLE
Style for 'Contact' on support page is incorrect.

### ISSUE THREAD

**Issue by notthetup** [subnero1/subnero1.github.io#58]
![IMG_2607](https://user-images.githubusercontent.com/553140/55782360-ae98cd80-5ade-11e9-8cc9-4da294a83300.PNG)

**Comment by AnneThKu** [comment]
Fixed. The issue was in mobile version.

**Comment by notthetup** [comment]
![IMG_67F4FFCA9F8F-1](https://user-images.githubusercontent.com/553140/56182296-0df95f00-6044-11e9-8005-726a2e9106c4.jpeg)
