### ISSUE TITLE
Banner Images

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#59]
Can we have the below banner images in a different colour background instead of white.

![Screenshot 2019-04-17 at 11 45 22 AM](https://user-images.githubusercontent.com/42397354/56259635-4fead980-6106-11e9-9b6e-51c85219c6c5.png)

![Screenshot 2019-04-17 at 11 44 41 AM](https://user-images.githubusercontent.com/42397354/56259611-39448280-6106-11e9-9a37-7536a4c5ae6c.png)

 May be a blue or water background as below.
![Screenshot 2019-04-17 at 11 42 17 AM](https://user-images.githubusercontent.com/42397354/56259543-f97d9b00-6105-11e9-9d32-6cec539989d4.png)

![Screenshot 2019-04-17 at 11 42 37 AM](https://user-images.githubusercontent.com/42397354/56259590-26ca4900-6106-11e9-8aff-a4e6fff920e6.png)

**Comment by manuignatius** [comment]
![banner-pulse-aRecorder](https://user-images.githubusercontent.com/4144181/57370528-f33d8480-71c2-11e9-8957-48cc7f69bfb9.jpg)
Does this work?

**Comment by manuignatius** [comment]
<img width="1899" alt="Screen Shot 2019-05-08 at 7 05 16 PM" src="https://user-images.githubusercontent.com/4144181/57371018-406e2600-71c4-11e9-9a98-2739b36f2577.png">

**Comment by notthetup** [comment]
I like the colour in the background, but this blue looks strange. Maybe a little more texture?

**Comment by manuignatius** [comment]
<img width="1897" alt="Screen Shot 2019-05-09 at 9 14 50 AM" src="https://user-images.githubusercontent.com/4144181/57424470-5e7e6980-724a-11e9-8e7b-0efe162a01fa.png">
<img width="1873" alt="Screen Shot 2019-05-09 at 9 15 05 AM" src="https://user-images.githubusercontent.com/4144181/57424491-79e97480-724a-11e9-9c2d-bc9493c22190.png">

What about these?

**Comment by AnneThKu** [comment]
It looks a bit lighter. May be a more deeper colour as in Solutions page.

![Screenshot 2019-05-09 at 4 03 24 PM](https://user-images.githubusercontent.com/42397354/57437338-2429c200-7274-11e9-9b35-1c47f0666e50.png)

**Comment by manuignatius** [comment]
When there is texture in background, if it is dark, it will overwhelm the actual image and there will not be enough separation between background and foreground. Thats why the updated bg is lighter.

Check the evo bg attached before.

**Comment by notthetup** [comment]
The waves feel like the modems being tossed about. :(

**Comment by notthetup** [comment]
Ideas :  https://unsplash.com/photos/glJeHs0beDU

Or the top of this https://unsplash.com/photos/UCIZh0-OYPw

**Comment by manuignatius** [comment]
Uploading banner-pulse-aRecorder.jpg
![banner-pulse-aRecorder](https://user-images.githubusercontent.com/4144181/58693516-8aad8600-83c3-11e9-89c3-92c496912df6.jpg)


banner-pulse-custommodem.jpg
![banner-pulse-custommodem](https://user-images.githubusercontent.com/4144181/58693480-78cbe300-83c3-11e9-8b99-d1ab03a5ec42.jpg)
