### ISSUE TITLE
Add link to the product manuals on the support page.

### ISSUE THREAD

**Issue by AmyGibSubnero** [subnero1/subnero1.github.io#60]
Although the manuals are on the website at
https://subnero.com/support/wnc/manuals/

There is no link to this page from the support page.

**Comment by AmyGibSubnero** [comment]
Link will be added to main support page once final general manual has been made.

**Comment by AnneThKu** [comment]
The link will be added in Support page after the manuals are standardised. As for now, separate links for manuals will be created for the projects (Kriso, Alabama etc)
