### ISSUE TITLE
Use a generic image as default thumbnail image for pulse page

### ISSUE THREAD

**Issue by manuignatius** [subnero1/subnero1.github.io#63]
Currently the default image is that of the modems. 
![boxart-modem](https://user-images.githubusercontent.com/4144181/57579756-35bcd500-74d3-11e9-95c2-8097c1f769a0.jpg)

Use a generic image like unetstack or so

**Comment by manuignatius** [comment]
Filename: pulse-thumbnail-default.jpg

![pulse-thumbnail-default](https://user-images.githubusercontent.com/4144181/58692540-6355b980-83c1-11e9-9ec6-50d008c5e13c.jpg)

**Comment by AnneThKu** [comment]
Also the thumbnail images to be made clickable
