### ISSUE TITLE
To upload updated leaflets

### ISSUE THREAD

**Issue by Florie25** [subnero1/subnero1.github.io#69]
We would need to upload the latest version of the leaflets for modems for all pages (Platinum, Silver, and Research) and UnetStack, as attached. (3 documents)
https://subnero.com/brochures/subnero-modemforauv.pdf
https://subnero.com/products/platinum.html
https://subnero.com/products/unet.html
https://subnero.com/brochures/unetstack.pdf

@manuignatius  @notthetup  do we want to delete the technical specs from the website itself? They will now appear in the leaflet.

[Subnero Modem v4.0- Out (1).pdf](https://github.com/subnero1/subnero1.github.io/files/3264555/Subnero.Modem.v4.0-.Out.1.pdf)
[Subnero Modem v4.0 - In.pdf](https://github.com/subnero1/subnero1.github.io/files/3264556/Subnero.Modem.v4.0.-.In.pdf)

**Comment by manuignatius** [comment]
Please use this one: https://drive.google.com/open?id=1N4mmFktz0VFHGtKUM51BLasZTUx4ELY-

**Comment by notthetup** [comment]
I am guessing this is done.
