### ISSUE TITLE
Website images and content to be aligned to Unetstack3

### ISSUE THREAD

**Issue by AnneThKu** [subnero1/subnero1.github.io#87]
The Unetstack image in https://subnero.com/products/ page and the content in https://subnero.com/products/unet.html may have to be updated with the Unetstack3 release. Any views/comments on this?

**Comment by AnneThKu** [comment]
The links in the below statements to be fixed.
- UnetStack consists of a collection of software agents that provide [well-defined services](https://unetstack.net/agent-ref.html)
- The simulator is available free-of-charge for download from [www.unetstack.net](https://unetstack.net/downloads.html)
- A simple script written in a [domain-specific language (DSL)](https://unetstack.net/simulation-dsl.html) allows users to describe a simulation scenario in a natural way.
- UnetStack Newsletter links (26-10-2013)
- Support page links

**Comment by manuignatius** [comment]
In the products page, now its not showing anything. Which picture are you suggesting to replace with? The circular UnetStack3 logo? It will then be a "round picture in a square space"

No sure which picture you are suggesting in the unet.html page

**Comment by AnneThKu** [comment]
In products page, I was asking about this one, if we want to change it.
![image](https://user-images.githubusercontent.com/42397354/65576310-4e221d80-dfa4-11e9-9695-bc2930a9a917.png)

In unet.html page, 
![image](https://user-images.githubusercontent.com/42397354/65576542-c38dee00-dfa4-11e9-848e-bad574403900.png)

**Comment by manuignatius** [comment]
For 1, what do you propose to replace with? Additionally, the products page is not showing that image now in the iMac:
<img width="400" alt="Screenshot 2019-09-25 at 3 02 21 PM" src="https://user-images.githubusercontent.com/4144181/65577031-9ee64600-dfa5-11e9-8c24-f613be45b960.png">


For 2, yes, I vote to replace it with this:

<img width="400" alt="Screenshot 2019-09-25 at 3 02 54 PM" src="https://user-images.githubusercontent.com/4144181/65577037-a3aafa00-dfa5-11e9-8170-81d9bb9d6da7.png">

**Comment by AnneThKu** [comment]
I was thinking this image... for products page.
![image](https://user-images.githubusercontent.com/42397354/65577472-701c9f80-dfa6-11e9-9a37-c96319dc56a6.png)

**Comment by mchitre** [comment]
@AnneThKu is there something you need me to do for this?

**Comment by AnneThKu** [comment]
Nothing more to be done for the issue. The images and links are updated.
